version: "3"

services:
  web:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn myblog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
      - POSTGRES_DB=blog_prod
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
